# Generated by Django 2.2.4 on 2022-09-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
