# Generated by Django 2.2.4 on 2022-09-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default='programming language'),
            preserve_default=False,
        ),
    ]
